---
title: 'About Us'
output: 
  html_document:
    toc: true
    toc_float: true
    css: styles.css
---

### Laura Henze 
[Laura](https://github.com/lah2231) is a medical doctor from Germany with experience in internal medicine and emergency medicine. She is currently pursuing a Master's degree in biomedical informatics. In her free time, she enjoys exploring New York, attending theater performances, and taking ballet classes.

### Rebecca Shyu
[Rebecca](https://github.com/rysgpd) is a 3rd year PhD student in the Department of Biomedical Informatics. Her favorite tennis player is Roger Federer!

### HsiYu Chen  
[HsiYu](https://github.com/xcindychen) is an MD graduate currently pursuing a master’s degree in Biomedical Informatics at Columbia University. She enjoys climbing, scuba diving, and exploring the great outdoors!

### Stacey Dai  
[Stacey](https://github.com/sd3730) is a second-year MPH student in the Epidemiology department. In her free time, she enjoys crocheting and exploring the city.

### Vaiju Raja 
[Vaiju](https://github.com/spicypeanut17) is a Toxicology student with a background in Global Health Epidemiology and Disease Control. She prefers basketball and soccer over tennis!

