---
title: "data_cleaning"
author: "Rebecca Shyu"
date: "2024-11-20"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

```{r import_data, message=FALSE}
slams = c("Australian Open", "Roland Garros", "Wimbledon", "Us Open", "US Open")

df_2014 = read_csv("data/atp_matches_2014.csv") %>% 
  janitor::clean_names() %>% 
  filter(
    tourney_name %in% slams
  )

df_2015 = read_csv("data/atp_matches_2015.csv") %>% 
  janitor::clean_names() %>% 
  filter(
    tourney_name %in% slams
  )

df_2016 = read_csv("data/atp_matches_2016.csv") %>% 
  janitor::clean_names() %>% 
  filter(
    tourney_name %in% slams
  )

df_2017 = read_csv("data/atp_matches_2017.csv") %>% 
  janitor::clean_names() %>% 
  filter(
    tourney_name %in% slams
  )

df_2018 = read_csv("data/atp_matches_2018.csv") %>% 
  janitor::clean_names() %>% 
  filter(
    tourney_name %in% slams
  )

df_2019 = read_csv("data/atp_matches_2019.csv") %>% 
  janitor::clean_names() %>% 
  filter(
    tourney_name %in% slams
  )

df_2020 = read_csv("data/atp_matches_2020.csv") %>% 
  janitor::clean_names() %>% 
  filter(
    tourney_name %in% slams
  ) #wimbledon was cancelled this year due to COVID

df_2021 = read_csv("data/atp_matches_2021.csv") %>% 
  janitor::clean_names() %>% 
  filter(
    tourney_name %in% slams
  ) 

df_2022 = read_csv("data/atp_matches_2022.csv") %>% 
  janitor::clean_names() %>% 
  filter(
    tourney_name %in% slams
  )

df_2023 = read_csv("data/atp_matches_2023.csv") %>% 
  janitor::clean_names() %>% 
  filter(
    tourney_name %in% slams
  )

seed_types = c("WC", "Q", "LL")

df_2024 = read_csv("data/atp_matches_2024.csv") %>% 
  janitor::clean_names() %>% 
  filter(
    tourney_name %in% slams
  ) %>% 
  mutate(
    winner_entry = ifelse(winner_seed %in% seed_types, winner_seed, winner_entry),
    winner_seed = ifelse(winner_seed %in% seed_types, NA, winner_seed),
    winner_seed = as.double(winner_seed),
    loser_entry = ifelse(loser_seed %in% seed_types, loser_seed, loser_entry),
    loser_seed = ifelse(loser_seed %in% seed_types, NA, loser_seed),
    loser_seed = as.double(loser_seed)
  )# only australian open since it goes up until april


total_df = bind_rows(df_2014, df_2015, df_2016, df_2017, df_2018, df_2019, df_2020, df_2021, df_2022, df_2023, df_2024) %>% 
  mutate(
    tourney_name = ifelse(tourney_name == "Us Open", "US Open", tourney_name),
    tourney_date = as.Date(as.character(tourney_date), format = "%Y%m%d"),
    tourney_name = as.factor(tourney_name),
    winner_hand = as.factor(winner_hand),
    winner_ioc = as.factor(winner_ioc),
    loser_hand = as.factor(loser_hand),
    loser_ioc = as.factor(loser_ioc),
    round = as.factor(round)
  ) %>% 
  select(-c(tourney_id, surface, draw_size, tourney_level, match_num, best_of))

summary(total_df)

write_csv(total_df, "data/cleaned_df.csv")
```

```{r}
# split into losers and winners dataset
df2 = read.csv("data/cleaned_df.csv")
df_updated = read.csv("data/cleaned_data_with_full_2024_data_added.csv")

winner_df = df_updated %>% 
  select(1:10, 19:30, 40, 41) %>% 
  mutate(
    won = 1
  ) %>% 
  rename_all(~stringr::str_replace(.,"^winner_","")) %>% 
  rename_all(~stringr::str_replace(.,"^w_",""))


loser_df = df_updated %>% 
  select(1, 2, 11:21, 31:39, 42, 43) %>% 
  mutate(
    won = 0
  ) %>% 
  rename_all(~stringr::str_replace(.,"^loser_","")) %>% 
  rename_all(~stringr::str_replace(.,"^l_",""))

player_df = rbind(winner_df, loser_df)

write_csv(player_df, "data/winners_losers_df_updated.csv")

```

