---
title: "Statistic Analysis"
---

## Rankings by score, player age information; Compare seed scores to final score

```{r setup, echo = FALSE, warning = FALSE, message = FALSE}
library(tidyverse)
library(ggplot2)
library(lubridate)
library(dplyr)
library(plotly)
library(leaflet)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
  fig.width = 10,
  fig.asp = .6,
  out.width = "100%",
	dpi=300
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

df = read.csv("data/cleaned_df_webscraping_data_added.csv")
df2 = read.csv("data/cleaned_df.csv")

```

```{r seed_distrib, echo = FALSE, warning = FALSE, message = FALSE}

df2 %>% 
  filter(
    round == "F"
  ) %>% 
  ggplot(aes(x = winner_seed)) +
  geom_histogram(binwidth = 1) +
  scale_x_continuous(breaks=seq(1,20,1))+
  scale_y_continuous()+
  labs(
    title = "Distribution of Seeds of Grand Slam Winners from 2014-2024",
    x = "Seed",
    y = "Number of Winners"
    ) +
  theme(plot.title = element_text(hjust = 0.5))
  

```

